server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:   # 自此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称，用于binding整合
          type: rabbit # 消息组件类型
          environment:  # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.70.190
                port: 5672
                username: lollipop
                password: lollipop
      bindings:   # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的exchange名称定义
          content-type: application/json # 设置消息类型，本次为json
          binder: defaultRabbit  # 设置要绑定的消息服务的具体设置
          group: Lollipop-A   # 分组（避免重复消费），同组消费者属于竞争关系,不会发生重复消费 PS:添加group属性后支持消息持久化，当服务重新恢复正常运行时，会从MQ中执行未消费的记录

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔
    instance-id: consumer-8803.com
    prefer-ip-address: true # 访问的路径变为IP地址
