server:
  port: 3344
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lollipop1024/cloud2021-config-center.git
          search-paths:
            - cloud2021-config-center
          username: 2607166703@qq.com
          password: lollipop@1024.gitee
      label: master
  http:
    # 解决配置文件中中文乱码
    encoding:
      force: true
      charset: utf-8
      enabled: true
  # RabbitMQ配置
  rabbitmq:
    host: 192.168.70.190
    port: 5672
    username: lollipop
    password: lollipop
    virtual-host: /

# RabbitMQ相关配置，暴露bus刷新配置的端点 实现配置中心修改后，配置客户端动态刷新-在gitee上修改配置后，再发送curl -X POST "http://localhost:3344/actuator/bus-refresh"，使所有配置客户端同步配置
# 更新具体的客户端：curl -X POST "http://localhost:3344/actuator/bus-refresh/cloud-config-client:3355"
management:
  endpoints:  # 暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'