server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
#    password: marshmallow

  zipkin:
    # zipkin控制台访问地址
    base-url: http://localhost:9411
    sleuth:
      sampler:
        # 采样率值介于0到1之间，1则表示全部采集，一般设置为0.5
      probability: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lollipop.springcloud.entity
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7001.com:7002/eureka
    # 单机版
    # defaultZone: http://localhost:7001/eureka
  # 指定主机名称
  instance:
    instance-id: payment8001
    # 访问路径显示ip地址
    prefer-ip-address: true
