server:
  port: 80
spring:
  application:
    # 注册到注册中心的服务名称
    name: cloud-consumer-order
  cloud:
    zookeeper:
      # 虚拟机中docker中的zookeeper地址
      connect-string: 192.168.70.130:2181
#      connect-string: 192.168.247.128:2181