server:
  port: 8001

spring:
  application:
    name: cloud-hystrix-payment-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 集群版
      #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7001.com:7002/eureka
      # 单机版
      defaultZone: http://eureka7001.com:7001/eureka
  # 指定主机名称
  instance:
    instance-id: payment8001
    # 访问路径显示ip地址
    prefer-ip-address: true
